name: Docker Orange Pi Zero Alpine Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker Image
      run: docker build -t orange-pi-zero-alpine-build:20.04 ./docker
    - name: Build Orangepizero Alpine Image
      run: docker run -e CORES=$(grep -c processor /proc/cpuinfo) -v $PWD:/root/orange-pi-zero-alpine/ orange-pi-zero-alpine-build:20.04
    - name: Export Version
      run: echo "version=$(cat ALPINE_VERSION)" >> $GITHUB_OUTPUT
      id: version
    - name: Upload Build Artifact Files
      uses: actions/upload-artifact@v4
      with:
        name: orangepi-zero-alpine-image-${{ steps.version.outputs.version }}
        path: orangepi-zero-alpine-image-${{ steps.version.outputs.version }}/
    - name: Create Release
      uses: ncipollo/release-action@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        name: ${{ steps.version.outputs.version }}
        tag: v${{ steps.version.outputs.version }}
        bodyFile: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Upload Kernel Artifacts
      uses: svenstaro/upload-release-action@v2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: orangepi-zero-alpine-image-${{ steps.version.outputs.version }}.tar.gz
        asset_name: orangepi-zero-alpine-image-${{ steps.version.outputs.version }}.tar.gz
        tag: v${{ steps.version.outputs.version }}
